# Generated by Django 4.2.4 on 2023-08-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_lessons_books_lessons_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='lesson_title',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
