# Generated by Django 4.2.4 on 2024-05-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_lessons_lesson_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='book',
        ),
    ]
