# Generated by Django 4.2.4 on 2024-05-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0003_remove_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined')], default='pending', max_length=40),
        ),
    ]
